import = [ "~/.config/alacritty/theme.toml" ]

[font]
size = 14.0

[font.offset]
y = 1
[font.normal]
family = "M+ 2m"
style = "regular"
[font.bold]
family = "M+ 2m"
style = "bold"

# [font.normal]
# family = "Source Code Pro"
# style = "Medium"
# [font.bold]
# family = "Source Code Pro"
# style = "Bold"

